/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: misterdevious (https://sketchfab.com/misterdevious)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/cemetery-statuary-lape-ea9eac9cee4b4397aad409f8c522467e
title: Cemetery Statuary - Lape
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Statue(props) {
    const group = useRef()
  const { nodes, materials } = useGLTF('/statue/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.99, -2.02, 5.29]} rotation={[-0.27, 0.6, 1.93]} />
        <group scale={0.6}>
          <mesh geometry={nodes.default_0.geometry} material={nodes.default_0.material} castShadow/>
          <mesh geometry={nodes.default_0_1.geometry} material={nodes.default_0_1.material} castShadow />
          <mesh geometry={nodes.default_0_2.geometry} material={nodes.default_0_2.material} castShadow/>
          <mesh geometry={nodes.default_0_3.geometry} material={nodes.default_0_3.material} castShadow/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')

export default Statue